kind: Deployment
apiVersion: apps/v1
metadata:
  name: greenapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
       - name: app
         image: leaddevops/kubeserve:v2
